-- Add ai_generated_video flag to materials table
ALTER TABLE public.materials 
ADD COLUMN IF NOT EXISTS ai_generated_video boolean DEFAULT false;

-- Add comment for documentation
COMMENT ON COLUMN public.materials.ai_generated_video IS 'Indicates if the video was generated by AI';