// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oprscgxsfldzydbrbioz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wcnNjZ3hzZmxkenlkYnJiaW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzY0ODIsImV4cCI6MjA3MjY1MjQ4Mn0.qJapmxzavtnEWZ2j5RpW6nb3fppcaOiKCxApn77DG7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});